import { Divider } from "antd";
import axios from "axios";
import Head from "next/head";
import FilmPoster from "../components/film-poster";
import FilmSlider from "../components/film-slider";
import HeaderSlider from "../components/slider";

export default function Home({ data }) {
  console.log(data, "is data");

  return (
    <div>
      <Head>
        <title>صفحه اصلی || تاپ فیلم</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HeaderSlider />
        <Divider orientation="right">
          <h2>برترین فیلم ها</h2>
        </Divider>
        <FilmSlider key="popular" data={data.popular} />
        <Divider orientation="right">
          <h2>آخرین فیلم ها</h2>
        </Divider>
        <FilmSlider dark key="recent" data={data.recent} />
        <FilmPoster />
        <Divider orientation="right">
          <h2>قدیمی ترین فیلم ها</h2>
        </Divider>
        <FilmSlider key="old" data={data.old} dark />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const data = (await axios.get("/api/films")).data;

  return {
    props: {
      data,
    },
  };
}
